feat(core): rules setup
edenspiekermann/espi-stylelint-config pull request #2
Opened 2020-10-13 09:42 UTC by YvesRijckaert

2020-10-14 10:12 UTC, schorfES requested changes
I've added some comments. Please also update the README.md according the different rulesets.

2020-10-14 10:12 UTC, schorfES commented on rules/core.js
> +    /* Specify the order of properties within declaration blocks. */
Can we separate each comment + rule with a new line for a better readability?

```
// Specify the alphabetical order of properties within declaration blocks.
// https://github.com/hudochenkov/stylelint-order/tree/master/rules/properties-alphabetical-order
"order/properties-alphabetical-order": null,

// Specify the order of properties within declaration blocks.
// https://github.com/hudochenkov/stylelint-order/tree/master/rules/properties-order
"order/properties-order": [],
```

(I've also change the comment style. Doesn't make sense to me to use multiline-comments in a single line. Break the line between 80-96 characters)

2020-10-14 10:12 UTC, schorfES commented on rules/styled-components.js
> +    "order/properties-alphabetical-order": null,
Please do not re-introduce rules from core. This file should only extend the core configuration. The usage in the stylelint configuration should look like:

```
{
  "extends": [
    "@edenspiekermann/stylelint-config",
    "@edenspiekermann/stylelint-config/styled-components"
  ]
}
```

2020-10-14 10:12 UTC, schorfES commented on rules/tailwind.js
> +    "order/properties-alphabetical-order": null,
Please do not re-introduce rules from core. This file should only extend the core configuration. The usage in the stylelint configuration should look like:

```
{
  "extends": [
    "@edenspiekermann/stylelint-config",
    "@edenspiekermann/stylelint-config/tailwind"
  ]
}
```

or

```
{
  "extends": [
    "@edenspiekermann/stylelint-config",
    "@edenspiekermann/stylelint-config/sass",
    "@edenspiekermann/stylelint-config/tailwind"
  ]
}
```

2020-10-14 10:12 UTC, schorfES commented on rules/core.js
> +  ignoreFiles: ["./.cache/**/*", "./node_modules/**/*", "./public/**/*"],
I would suggest to only apply this to the `node_modules`. The rest is a project specific configuration. Please double-check if stylelint needs to ignore `node_modules` or ignores them by default...

2020-10-14 10:12 UTC, schorfES commented on package.json
> +    "prettier",
Prettier?

2020-10-19 06:59 UTC, schorfES requested changes
There are a lot duplicate rules. Each rule should be placed in the most generic rules-set file. If you want to configure your project for example to use with styled-components, you need to put...

```
extends: [
  '@edenspiekermann/stylelint-config',
  '@edenspiekermann/stylelint-config/rules/styled-components',
]
```

...into you config file. There is no need to replicate rules from `@edenspiekermann/stylelint-config/rules/core` into `@edenspiekermann/stylelint-config/rules/styled-components`.

2020-10-19 06:59 UTC, schorfES commented on rules/sass.js
> +    '@edenspiekermann/stylelint-config',
Why self-extending?

2020-10-19 06:59 UTC, schorfES commented on rules/styled-components.js
> +    '@edenspiekermann/stylelint-config',
Why self-extending?

2020-10-19 06:59 UTC, schorfES commented on rules/tailwind.js
> +    '@edenspiekermann/stylelint-config',
Why self-extending?

2020-10-19 06:59 UTC, schorfES commented on rules/styled-components.js
> +    'order/properties-alphabetical-order': null,
No need to duplicate rules from an other rules set that is more generic.

2020-10-19 13:21 UTC, YvesRijckaert commented on rules/core.js
> +    // There must always be an empty line before at-rules.
wrong documentation link

2020-10-19 13:25 UTC, YvesRijckaert commented on rules/core.js
> +    'color-named': 'always-where-possible',
back to only hex

2020-10-19 13:29 UTC, YvesRijckaert commented on rules/core.js
> +    'color-named': 'always-where-possible',
also include a rule for color-hex-length (use long)

2020-10-19 13:33 UTC, YvesRijckaert commented on rules/core.js
> +    'number-max-precision': 2,
use 3

2020-10-19 13:35 UTC, YvesRijckaert commented on rules/core.js
> +    'number-leading-zero': 'never',
always

2020-10-19 13:38 UTC, YvesRijckaert commented on rules/core.js
> +    'selector-list-comma-newline-after': null,
always-multi-line

2020-10-19 13:40 UTC, YvesRijckaert commented on rules/core.js
> +    'selector-max-universal': 0,
use 1

2020-10-19 13:41 UTC, YvesRijckaert commented on rules/core.js
> +    'selector-no-vendor-prefix': true,
test if it works with scrollbar

2020-10-19 13:46 UTC, YvesRijckaert commented on rules/sass.js
> +  ],
rule for mixins on top of the declaration

2020-10-19 13:49 UTC, YvesRijckaert commented on rules/styled-components.js
> +  rules: {
remove duplicates from here that we already defined in core

2020-10-19 13:52 UTC, YvesRijckaert commented on rules/styled-components.js
> +      '^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$',
remove from first question mark to third question mark

2020-10-19 13:52 UTC, YvesRijckaert commented on rules/styled-components.js
> +      '^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$',
(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?

2020-10-19 13:52 UTC, YvesRijckaert commented on rules/tailwind.js
> +  rules: {
delete duplicates that are already defined in core

2020-10-19 13:53 UTC, YvesRijckaert commented on rules/styled-components.js
> +    'selector-class-pattern':
make a separate rule for BEM

2020-10-19 13:54 UTC, YvesRijckaert commented on rules/tailwind.js
> +    'function-parentheses-space-inside': null,
change to never

2020-10-19 13:54 UTC, YvesRijckaert commented on rules/tailwind.js
> +    'function-parentheses-space-inside': null,
place in core

2020-10-19 13:55 UTC, YvesRijckaert commented on rules/tailwind.js
> +    'scss/at-import-partial-extension-blacklist': null,
place in SASS rule file

2020-10-23 10:34 UTC, schorfES requested changes
Still some small issues. Please also add a section of each ruleset to the README.md

2020-10-23 10:34 UTC, schorfES commented on rules/bem.js
> +  extends: [
This rule-set still extends itself.

2020-10-23 10:34 UTC, schorfES commented on rules/sass.js
> +    '@edenspiekermann/stylelint-config/rules/sass',
This rule-set still extends itself.

2020-10-23 10:34 UTC, schorfES commented on rules/styled-components.js
> +    '@edenspiekermann/stylelint-config/rules/styled-components',
This rule-set still extends itself.

2020-10-23 10:34 UTC, schorfES commented on rules/tailwind.js
> +    '@edenspiekermann/stylelint-config/rules/tailwind',
This rule-set still extends itself.

2020-10-23 10:34 UTC, schorfES commented on rules/tailwind.js
> +    'at-rule-no-unknown': [null],
To disable this rule we need to set...
```suggestion
    'at-rule-no-unknown': null,
```

2020-10-26 11:27 UTC, schorfES approved these changes

2020-11-05 11:25 UTC, merged